//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoPublicacion
    {
        public int Id { get; set; }
        public int Cod { get; set; }
        public string Descripcion { get; set; }
        public string Motivo { get; set; }
        public string PathPDF { get; set; }
        public bool ErrorPDF { get; set; }
        public string ErrorPDFMotivo { get; set; }
        public Nullable<int> TransaccionId { get; set; }
        public Nullable<long> CuitId { get; set; }
        public Nullable<int> PuntoDeVentaId { get; set; }
        public Nullable<int> TipoComprobanteId { get; set; }
        public Nullable<int> NroCbte { get; set; }
    }
}
