//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante
    {
        public int TransaccionId { get; set; }
        public long CuitId { get; set; }
        public int PuntoDeVentaId { get; set; }
        public int TipoComprobanteId { get; set; }
        public int NroCbte { get; set; }
        public string TipoDocCliente { get; set; }
        public string NroDocCliente { get; set; }
        public double Imp_Total { get; set; }
        public System.DateTime FechaCbte { get; set; }
        public string Cae { get; set; }
        public Nullable<System.DateTime> FechaVto { get; set; }
        public string Resultado { get; set; }
        public string Motivo { get; set; }
        public Nullable<int> Error { get; set; }
        public string ErrorDesc { get; set; }
        public string RazonSocialCliente { get; set; }
        public string CodigoCliente { get; set; }
        public Nullable<long> RequestAFIPId { get; set; }
        public string MonedaId { get; set; }
        public string RolEmisorId { get; set; }
        public string RolReceptorId { get; set; }
        public Nullable<System.DateTime> FechaProceso { get; set; }
        public Nullable<double> TipoDeCambio { get; set; }
        public Nullable<long> CuitRolReceptorId { get; set; }
        public string IdentificacionReceptorComfiar { get; set; }
        public int TipoIdentificacionReceptorComfiar { get; set; }
        public int EstadoEmision { get; set; }
        public string UsuarioAnulacion { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public string MotivoAnulacion { get; set; }
        public Nullable<int> Indice { get; set; }
        public string TipoCodigoAutorizacion { get; set; }
        public Nullable<int> TransaccionResumenAnulacion { get; set; }
        public Nullable<int> EstadoTransaccionResumen { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string UsuarioAprobacion { get; set; }
        public Nullable<bool> AprobacionParcial { get; set; }
        public Nullable<System.DateTime> FechaFirmado { get; set; }
        public Nullable<int> EstadoPublicacionId { get; set; }
        public Nullable<bool> AceptacionRechazoProcesado { get; set; }
        public byte[] Xml { get; set; }
    }
}
